package org.dexpace.sdk.core.http.auth

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertSame
import kotlin.test.assertTrue

class AuthSchemeTest {
    @Test
    fun `enum exposes all expected entries`() {
        val expected =
            setOf(
                AuthScheme.OAUTH2,
                AuthScheme.API_KEY,
                AuthScheme.BASIC,
                AuthScheme.DIGEST,
                AuthScheme.NO_AUTH,
            )
        assertEquals(expected, AuthScheme.entries.toSet())
        assertEquals(5, AuthScheme.entries.size)
    }

    @Test
    fun `values returns all entries in declaration order`() {
        val arr = AuthScheme.values()
        assertEquals(5, arr.size)
        assertSame(AuthScheme.OAUTH2, arr[0])
        assertSame(AuthScheme.API_KEY, arr[1])
        assertSame(AuthScheme.BASIC, arr[2])
        assertSame(AuthScheme.DIGEST, arr[3])
        assertSame(AuthScheme.NO_AUTH, arr[4])
    }

    @Test
    fun `valueOf round-trips every entry name`() {
        for (entry in AuthScheme.entries) {
            assertSame(entry, AuthScheme.valueOf(entry.name))
        }
    }

    @Test
    fun `name and ordinal are exposed`() {
        // Trivial assertion that touches the synthetic name/ordinal generated by the
        // compiler — keeps coverage honest if the enum is ever extended.
        assertEquals("OAUTH2", AuthScheme.OAUTH2.name)
        assertEquals(0, AuthScheme.OAUTH2.ordinal)
        assertTrue(AuthScheme.NO_AUTH.ordinal >= 0)
    }
}
